apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: grafana-image-renderer
    app.kubernetes.io/name: grafana-image-renderer
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.0.1
  name: grafana-image-renderer
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana-image-renderer
      app.kubernetes.io/name: grafana-image-renderer
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/component: grafana-image-renderer
        app.kubernetes.io/name: grafana-image-renderer
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 2.0.1
    spec:
      containers:
      - env:
        - name: ENABLE_METRICS
          value: "true"
        image: grafana/grafana-image-renderer:2.0.1
        name: grafana-image-renderer
        ports:
        - containerPort: 8081
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      nodeSelector:
        beta.kubernetes.io/os: linux