kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage