---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: line-notify-gateway-svc
  name: line-notify-gateway-svc
  namespace: monitoring
spec:
  ports:
  - name: "api"
    port: 5000
    targetPort: 5000
  selector:
    app: line-notify-gateway
status:
  loadBalancer: {}