---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: line-notify-gateway
  name: line-notify-gateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line-notify-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: line-notify-gateway
    spec:
      containers:
      - image: a123453906/line-notify-gateway:latest
        name: line-notify-gateway
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 5000
      restartPolicy: Always
status: {}