apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  labels:
    app.kubernetes.io/name: ingress-nginx
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      release: prometheus-operator
  namespaceSelector:
    matchNames:
    - ingress-nginx