apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-prometheus
  labels:
    type: monitoring-prometheus
  namespace: monitoring
spec:
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path:  /home/nccu/observe/kube-prometheus/pv/pv0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
